---
- name: iptables -t nat -I PREROUTING -p {{ _protocol }} --dport {{ _self_port }} -j DNAT --to-destination {{ _dest_addr }}:{{ _dest_port }}
  iptables:
    state: "{{ 'absent' if remove else 'present' }}"
    table: nat
    action: insert
    chain: PREROUTING
    protocol: "{{ _protocol }}"
    destination_port: "{{ _self_port }}"
    jump: DNAT
    to_destination: "{{ _dest_addr }}:{{ _dest_port }}"
  loop: "{{ ['tcp', 'udp'] if protocol == '' else [protocol] }}"
  loop_control:
    loop_var: _protocol
  when: self_port != "" or dest_port != ""

- name: iptables -t nat -I POSTROUTING -p {{ _protocol }} -d {{ _dest_addr }} --dport {{ _dest_port }} -j SNAT --to-source {{ _self_addr }}
  iptables:
    state: "{{ 'absent' if remove else 'present' }}"
    table: nat
    action: insert
    chain: POSTROUTING
    protocol: "{{ _protocol }}"
    destination: "{{ _dest_addr }}"
    destination_port: "{{ _dest_port }}"
    jump: SNAT
    to_source: "{{ _self_addr }}"
  loop: "{{ ['tcp', 'udp'] if protocol == '' else [protocol] }}"
  loop_control:
    loop_var: _protocol
  when: self_port != "" or dest_port != ""

- name: sysctl net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
  when: self_port != "" or dest_port != ""
