---
- name: iptables -t nat -I PREROUTING -p {{ _protocol }} --dport {{ _self_port }} -j DNAT --to-destination {{ _dest_addr }}:{{ _dest_port }}
  iptables:
    table: nat
    action: insert
    chain: PREROUTING
    protocol: "{{ _protocol }}"
    destination_port: "{{ _self_port }}"
    jump: DNAT
    to_destination: "{{ _dest_addr }}:{{ _dest_port }}"

- name: iptables -t nat -I POSTROUTING -p {{ _protocol }} -d {{ _dest_addr }} --dport {{ _dest_port }} -j SNAT --to-source {{ _self_addr }}
  iptables:
    table: nat
    action: insert
    chain: POSTROUTING
    protocol: "{{ _protocol }}"
    destination: "{{ _dest_addr }}"
    destination_port: "{{ _dest_port }}"
    jump: SNAT
    to_source: "{{ _self_addr }}"
