---
- name: Set up PREROUTING rule
  iptables:
    state: "{{ 'absent' if remove else 'present' }}"
    table: nat
    action: insert
    chain: PREROUTING
    protocol: "{{ _protocol }}"
    destination_port: "{{ _self_port }}"
    jump: DNAT
    to_destination: "{{ _dest_addr }}:{{ _dest_port }}"
  loop: "{{ ['tcp', 'udp'] if protocol == '' else [protocol] }}"
  loop_control:
    loop_var: _protocol
  notify: sysctl net.ipv4.ip_forward=1
  when: self_port != "" or dest_port != ""

- name: Set up POSTROUTING rule
  iptables:
    state: "{{ 'absent' if remove else 'present' }}"
    table: nat
    action: insert
    chain: POSTROUTING
    protocol: "{{ _protocol }}"
    destination: "{{ _dest_addr }}"
    destination_port: "{{ _dest_port }}"
    jump: SNAT
    to_source: "{{ _self_addr }}"
  loop: "{{ ['tcp', 'udp'] if protocol == '' else [protocol] }}"
  loop_control:
    loop_var: _protocol
  notify: sysctl net.ipv4.ip_forward=1
  when: self_port != "" or dest_port != ""
